name: "Cloudflare Cache Clear Github Action"
description: "GitHub Action to clear Cloudflare cache by zone name"
author: "Andrii Rozhkov"
branding:
    icon: "cloud"
    color: "orange"
runs:
    using: "docker"
    image: "Dockerfile"
